export const transferenciaEnviadas = [
    {
        id: 3,
        idOrdenante: 1,
        idBeneficiario: 2,
        importe: 50,
        concepto: "Regalo cumpleaño",
        fecha: new Date(),
    },
    {
        id: 9,
        idOrdenante: 1,
        idBeneficiario: 2,
        importe: 960,
        concepto: "Nomina",
        fecha: new Date(),
    },
    {
        id: 3,
        idOrdenante: 1,
        idBeneficiario: 2,
        importe: 200,
        concepto: "Alquiler",
        fecha: new Date(),
    },
    {
        id: 53,
        idOrdenante: 1,
        idBeneficiario: 2,
        importe: 600,
        concepto: "Alquiler",
        fecha: new Date(),
    },
    {
        id: 62,
        idOrdenante: 1,
        idBeneficiario: 2,
        importe: 550,
        concepto: "Alquiler",
        fecha: new Date(),
    },
    {
        id: 19,
        idOrdenante: 1,
        idBeneficiario: 2,
        importe: 1220,
        concepto: "Alquiler",
        fecha: new Date(),
    },
    ];