export const transferenciaEnviadas = [
    {
        id: 3,
        idOrdenante: 1,
        idBeneficiario: 2,
        importe: 50,
        concepto: "Asset Title Transfers",
        fecha: new Date(),
    },
    {
        id: 9,
        idOrdenante: 1,
        idBeneficiario: 2,
        importe: 960,
        concepto: "Loan Transfer",
        fecha: new Date(),
    },
    {
        id: 3,
        idOrdenante: 1,
        idBeneficiario: 2,
        importe: 200,
        concepto: "Payments",
        fecha: new Date(),
    },
    {
        id: 53,
        idOrdenante: 1,
        idBeneficiario: 2,
        importe: 600,
        concepto: "Brokerage Transfers",
        fecha: new Date(),
    },
    {
        id: 62,
        idOrdenante: 1,
        idBeneficiario: 2,
        importe: 550,
        concepto: "Trade trading tools",
        fecha: new Date(),
    },
    {
        id: 19,
        idOrdenante: 1,
        idBeneficiario: 2,
        importe: 1220,
        concepto: "Understanding Transfers",
        fecha: new Date(),
    },
    ];