export const transferenciaRecibidas = [
{
    id: 1,
    idOrdenante: 1,
    idBeneficiario: 2,
    importe: 50,
    concepto: "Regalo cumpleaño",
    fecha: new Date(),
},
{
    id: 2,
    idOrdenante: 1,
    idBeneficiario: 2,
    importe: 960,
    concepto: "Nomina",
    fecha: new Date(),
},
{
    id: 4,
    idOrdenante: 1,
    idBeneficiario: 2,
    importe: 200,
    concepto: "Alquiler",
    fecha: new Date(),
},
{
    id: 5,
    idOrdenante: 1,
    idBeneficiario: 2,
    importe: 600,
    concepto: "Alquiler",
    fecha: new Date(),
},
{
    id: 6,
    idOrdenante: 1,
    idBeneficiario: 2,
    importe: 550,
    concepto: "Alquiler",
    fecha: new Date(),
},
{
    id: 9,
    idOrdenante: 1,
    idBeneficiario: 2,
    importe: 1220,
    concepto: "Alquiler",
    fecha: new Date(),
},
];